### PR TITLE
Correctly handle address sizes for DW_CFA_set_loc

### LINKED ISSUE #102: Parsing `DW_CFA_set_loc` is wrong
We are currently parsing the address as a uleb, but it should be an address-sized integer and also if the fde's cie defines a non-zero segment size, the address is preceded by a segment.

### PR DESCRIPTION
**Pull request by mitsuhiko**
The current code does not correctly handle the the `DW_CFA_set_loc` instruction. It assumes the argument is uleb128 encoded but it's actually a fixed size integer depending on the address size. Mishandling this can cause the cfi iteration to consume garbage after an integer has been incorrectly read.

I was not sure however about how the current tests assume pointer sizes so for now I hardcoded this to be 8. This might have to become `sizeof::<usize>()`.

This fixes #102

### CODE REVIEW

**Comment by fitzgen** [comment]
I think your intuition was on the money regarding address sizes. From CI:

```
---- read::cfi::tests::test_parse_fde_32_ok stdout ----
thread 'read::cfi::tests::test_parse_fde_32_ok' panicked at 'assertion failed: `(left == right)`
  left: `Ok(FrameDescriptionEntry { offset: 0, length: 27, format: Dwarf32, cie: CommonInformationEntry { offset: 0, length: 100, format: Dwarf32, version: 4, augmentation: None, address_size: 8, segment_size: 0, code_alignment_factor: 3, data_alignment_factor: 2, return_address_register: Register(1), initial_instructions: EndianSlice { slice: [], endian: LittleEndian }, phantom: PhantomData }, initial_segment: 0, initial_address: 4276993775, address_range: 39, address_size: 4, augmentation: None, instructions: EndianSlice { slice: [0, 0, 0, 0, 0, 0, 0], endian: LittleEndian } })`,
 right: `Ok(FrameDescriptionEntry { offset: 0, length: 27, format: Dwarf32, cie: CommonInformationEntry { offset: 0, length: 100, format: Dwarf32, version: 4, augmentation: None, address_size: 8, segment_size: 0, code_alignment_factor: 3, data_alignment_factor: 2, return_address_register: Register(1), initial_instructions: EndianSlice { slice: [], endian: LittleEndian }, phantom: PhantomData }, initial_segment: 0, initial_address: 4276993775, address_range: 39, address_size: 8, augmentation: None, instructions: EndianSlice { slice: [0, 0, 0, 0, 0, 0, 0], endian: LittleEndian } })`', src/read/cfi.rs:3832:9
```

https://travis-ci.org/gimli-rs/gimli/jobs/478405308#L975 etc

**Comment by fitzgen** [comment]
Oh also -- this doesn't resolve the segments part of #355 so either that bug should be fixed in this PR too, or we shouldn't have the "fixes" thing in the PR comment so that issue is left open.

**Comment by mitsuhiko** [comment]
Going to change the sizes. The segment part I did not understand. I looked at what llvm does and I did not see any obvious difference other than the size aspect of the argument.

**Comment by mitsuhiko** [comment]
Did some changes to the tests but this needs a thorough review before merging. One of the tests already intentionally tries to test for a 64bit addressed dwarf32 but the second part of the test seems to assume native endianness if I'm not mistaken.

**Comment by fitzgen** [comment]
This fixes the failing test:

```diff
diff --git a/src/read/cfi.rs b/src/read/cfi.rs
index 5601986..9828081 100644
--- a/src/read/cfi.rs
+++ b/src/read/cfi.rs
@@ -4093,7 +4093,7 @@ mod tests {
             offset: 0,
             length: 0,
             format: Format::Dwarf32,
-            address_size: 8,
+            address_size: cie1.address_size,
             cie: cie1.clone(),
             initial_segment: 0,
             initial_address: 0xfeed_beef,
@@ -4106,7 +4106,7 @@ mod tests {
             offset: 0,
             length: 0,
             format: Format::Dwarf32,
-            address_size: 8,
+            address_size: cie2.address_size,
             cie: cie2.clone(),
             initial_segment: 0,
             initial_address: 0xfeed_face,
```

The expected FDEs' adress sizes need to match their corresponding CIEs' address sizes.

**Comment by fitzgen** [comment]
This fixes the failing test:

```diff
diff --git a/src/read/cfi.rs b/src/read/cfi.rs
index 5601986..9828081 100644
--- a/src/read/cfi.rs
+++ b/src/read/cfi.rs
@@ -4093,7 +4093,7 @@ mod tests {
             offset: 0,
             length: 0,
             format: Format::Dwarf32,
-            address_size: 8,
+            address_size: cie1.address_size,
             cie: cie1.clone(),
             initial_segment: 0,
             initial_address: 0xfeed_beef,
@@ -4106,7 +4106,7 @@ mod tests {
             offset: 0,
             length: 0,
             format: Format::Dwarf32,
-            address_size: 8,
+            address_size: cie2.address_size,
             cie: cie2.clone(),
             initial_segment: 0,
             initial_address: 0xfeed_face,
```

The expected FDEs that we parse need to have address sizes that match their corresponding CIEs (which got updated in your second commit, but the FDEs did not).

Fold this into the PR and we should be good to merge!

**Comment by mitsuhiko** [comment]
@fitzgen since the address size is already on the cie anyways i will change it so tha ti always use that data.

**Comment by fitzgen** [comment]
CI had passed, and then the most recent commit broke it again:

```
---- read::cfi::tests::test_parse_cfi_instruction_set_loc stdout ----
thread 'read::cfi::tests::test_parse_cfi_instruction_set_loc' panicked at 'assertion failed: `(left == right)`
  left: `EndianSlice { slice: [0, 0, 0, 0, 1, 2, 3, 4], endian: LittleEndian }`,
 right: `EndianSlice { slice: [1, 2, 3, 4], endian: LittleEndian }`', src/read/cfi.rs:4293:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    read::cfi::tests::test_parse_cfi_instruction_set_loc
```

**Comment by mitsuhiko** [comment]
I think the pass was spurious but i need to verify. I will fix this but i want to understand all test cases first to make sure they are correct :)

**Comment by philipc** [comment]
The segments support is low priority, and I'm not surprised LLVM doesn't support it. There's already some places in gimli where we return `Error::UnsupportedSegmentSize` for non-zero segment sizes.

File: src/read/cfi.rs [hunk 1]
```diff
@@ -3840,7 +3848,7 @@ mod tests {
             format: Format::Dwarf32,
             version: 4,
             augmentation: None,
-            address_size: 4,
+            address_size: mem::size_of::<usize>() as u8,
```
Comment (philipc) [inline src/read/cfi.rs]: You should be able to leave all these `DebugFrameCie` address sizes unchanged.

File: src/read/cfi.rs [hunk 2]
```diff
@@ -4272,12 +4280,12 @@ mod tests {
...
         let section = Section::with_endian(Endian::Little)
             .D8(constants::DW_CFA_set_loc.0)
-            .uleb(expected_addr)
+            .L64(expected_addr)
             .append_bytes(&expected_rest);
         let contents = section.get_contents().unwrap();
         let input = &mut EndianSlice::new(&contents, LittleEndian);
         assert_eq!(
-            CallFrameInstruction::parse(input),
+            CallFrameInstruction::parse(input, mem::size_of::<usize>() as u8),
```
Comment (philipc) [inline src/read/cfi.rs]: This address size must match the size of the `expected_addr` that is written, so it must be 8. It would also be worth adding a variant of this test that writes a 32 bit address.

File: src/read/cfi.rs [hunk 3]
```diff
@@ -4224,7 +4232,7 @@ mod tests {
...
```
Comment (philipc) [inline src/read/cfi.rs]: For most tests this address size doesn't matter, and I mildly prefer to set it as a constant (4 or 8) since that's simpler.
