### PR TITLE
Unit fixes

### LINKED ISSUE #132: Fix AttributeValue::value() for DW_AT_data_member_location
In DWARF version 2/3, `DW_FORM_data4`/`DW_FORM_data8` for a `DW_AT_data_member_location` attribute means a `.debug_loc` offset. But in DWARF version 4, it means a constant address offset.  So `AttributeValue::value()` needs to interpret these forms based on the DWARF version. However, we don't currently have access to the DWARF version in this function.

### PR DESCRIPTION
**Pull request by philipc**
Two fixes in unit.rs.  Also converted most of the unit.rs tests to test-assembler to help in writing tests for those fixes.

Fixes #132

### CODE REVIEW

**Comment by fitzgen** [comment]
Travis CI had some breakage with rust when they updated their rustup.sh. I think this PR caught that. It's since been fixed, and I've restarted the build.

File: src/unit.rs [hunk 1]
```diff
@@ -158,90 +154,6 @@ impl<'input, Endian> FallibleIterator for CompilationUnitHeadersIter<'input, End
     }
 }
 
-#[test]
```
Comment (fitzgen) [inline src/unit.rs]: Nice, thanks

File: src/unit.rs [hunk 2]
```diff
@@ -2403,21 +2403,144 @@ fn parse_type_unit_header<Endian>(input: EndianBuf<Endian>,
...
+                Format::Dwarf32 => self.L32(offset as u32),
+                Format::Dwarf64 => self.L64(offset as u64),
+            }
+        }
+
+        fn uleb(self, val: u64) -> Self {
+            let mut buf = Vec::new();
+            let written = leb128::write::unsigned(&mut buf, val).unwrap();
+            self.append_bytes(&buf[0..written])
+        }
```
Comment (fitzgen) [inline src/unit.rs]: My `.eh_frame` branch will introduce `test_util.rs` which has a trait with `uleb` and `sleb` methods. Once I get that merged, we will be able to make this trait simply require that one, and we can remove the duplication.

File: src/unit.rs [hunk 3]
```diff
@@ -2540,86 +2668,41 @@ mod tests {
...
+                debug_abbrev_offset: DebugAbbrevOffset(0x08070605),
+                address_size: 4,
+                format: Format::Dwarf32,
+                entries_buf: EndianBuf::new(expected_rest),
+            },
+            offset: DebugInfoOffset(0),
+        };
+        let section = Section::with_endian(Endian::Little)
+            .comp_unit(&mut unit64)
+            .comp_unit(&mut unit32);
```
Comment (fitzgen) [inline src/unit.rs]: Awesome, thanks so much for doing all this!
