### PR TITLE
Changes offsets to usize

### LINKED ISSUE #119: Should the offset newtypes be usize?
The values of DebugInfoOffset etc nearly always need to be used as usize, not u64. Perhaps we should change them to usize?

Note that `offset.0 as usize` will truncate if usize is smaller than u64, so if we validate this when parsing then I think overall this will be safer. I can't see any way to support offsets that are larger than the host's usize anyway, so I think failing when parsing is all we can do.

### PR DESCRIPTION
**Pull request by philipc**
Fixes #119

### CODE REVIEW

File: src/parser.rs [hunk 1]
```diff
@@ -575,3 +493,89 @@ pub fn parse_length_uleb_value<Endian>(input: EndianBuf<Endian>)
     let (rest, len) = try!(parse_unsigned_leb(input.into()));
     take(len as usize, EndianBuf::new(rest))
 }
+
+#[cfg(test)]
+mod tests {
```
Comment (fitzgen) [inline src/parser.rs]: Thanks!

File: src/parser.rs [hunk 2]
```diff
@@ -496,12 +496,16 @@ pub fn parse_length_uleb_value<Endian>(input: EndianBuf<Endian>)
 
 #[cfg(test)]
 mod tests {
+    extern crate test_assembler;
```
Comment (fitzgen) [inline src/parser.rs]: \o/

File: src/cfi.rs [hunk 3]
```diff
@@ -471,23 +473,22 @@ impl<'input, Endian> FrameDescriptionEntry<'input, Endian>
         where F: FnMut(DebugFrameOffset) -> Result<CommonInformationEntry<'input, Endian>>
     {
         let (rest_rest, (length, format, cie_pointer, rest)) = try!(parse_cfi_entry_common(input));
+        if is_cie_id(format, cie_pointer) {
+            return Err(Error::NotCiePointer);
```
Comment (fitzgen) [inline src/cfi.rs]: Good catch!

File: src/parser.rs [hunk 4]
```diff
@@ -348,6 +353,40 @@ pub fn parse_u32_as_u64<Endian>(input: EndianBuf<Endian>) -> Result<(EndianBuf<E
...
 
+/// Convert a `u64` to a `usize` and return it.
+#[doc(hidden)]
+#[inline]
+pub fn u64_to_offset(offset64: u64) -> Result<usize> {
+    let offset = offset64 as usize;
+    if offset as u64 == offset64 {
+        Ok(offset)
+    } else {
+        Err(Error::UnsupportedOffset)
```
Comment (fitzgen) [inline src/parser.rs]: We should have a test for the error branch. I don't see one in this commit, maybe in a follow up I haven't got to yet?

If not, it can be a follow up, if you'd prefer.

Comment (philipc) [inline src/parser.rs]: I'll try to add an i386 test in a followup.
