### PR TITLE
read: handle combination of DW_FORM_indirect and DW_FORM_implicit_const

### LINKED ISSUE #501: `assertion failed: self.form == constants::DW_FORM_implicit_const` when parsing debug info
I'm writing some fuzz targets for gimli, and they aren't quite ready to land themselves, but here is the first panic they've found.

### Assertion and Stack Trace

```
thread '<unnamed>' panicked at 'assertion failed: self.form == constants::DW_FORM_implicit_const', /home/fitzgen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==29607== ERROR: libFuzzer: deadly signal
    #0 0x555e1581c261 in __sanitizer_print_stack_trace /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_stack.cc:86:3
    #1 0x555e158ae816 in fuzzer::PrintStackTrace() (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x1ff816)
    #2 0x555e158c3136 in fuzzer::Fuzzer::CrashCallback() (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x214136)
    #3 0x7f5a12beb88f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1288f)
    #4 0x7f5a1260ee96 in __libc_signal_restore_set /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80
    #5 0x7f5a1260ee96 in gsignal /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:48
    #6 0x7f5a12610800 in abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:79
    #7 0x555e15abf546 in std::sys::unix::abort_internal::hd8d00ed29d7c9363 /rustc/1836e3b42a5b2f37fd79104eedbe8f48a5afdee6/src/libstd/sys/unix/mod.rs:167:5
    #8 0x555e15aa7825 in std::process::abort::h40f44407e56d98ba /rustc/1836e3b42a5b2f37fd79104eedbe8f48a5afdee6/src/libstd/process.rs:1623:14
    #9 0x555e15882346 in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h9ddf7c5a3d8e0247 (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x1d3346)
    #10 0x555e15aaee4c in std::panicking::rust_panic_with_hook::haa34a96a6dbd5a2e /rustc/1836e3b42a5b2f37fd79104eedbe8f48a5afdee6/src/libstd/panicking.rs:481:17
    #11 0x555e158486ef in std::panicking::begin_panic::hba6b078e1766f39a (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x1996ef)
    #12 0x555e15864982 in gimli::read::unit::parse_attribute::h5d16a0d1086b1174 (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x1b5982)
    #13 0x555e1587f2c0 in rust_fuzzer_test_input (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x1d02c0)
    #14 0x555e15882370 in __rust_try (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x1d3370)
    #15 0x555e15881faf in LLVMFuzzerTestOneInput (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x1d2faf)
    #16 0x555e158c3648 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x214648)
    #17 0x555e15885649 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x1d6649)
    #18 0x555e15890fc6 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0x1e1fc6)
    #19 0x555e1579b8d2 in main (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0xec8d2)
    #20 0x7f5a125f1b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #21 0x555e1579ba89 in _start (/home/fitzgen/gimli/fuzz/target/x86_64-unknown-linux-gnu/release/debug_info+0xeca89)
```

### Steps to Reproduce

```rust
    let debug_abbrev = DebugAbbrev::new(&[
        10,
        39,
        0,
        10,
        11,
        1,
        22,
        0,
        0,
        0,
        0,
        0,
        255,
        255,
        255,
        255,
        255,
    ], LittleEndian);
    let debug_info = DebugInfo::new(&[
        10,
        0,
        0,
        0,
        4,
        0,
        0,
        0,
        0,
        0,
        101,
        10,
        255,
        33,
        0,
        1,
    ], LittleEndian);

    let mut units = debug_info.units();
    while let Ok(Some(unit)) = units.next() {
        if let Ok(abbrevs) = unit.abbreviations(&debug_abbrev) {
            let mut cursor = unit.entries(&abbrevs);
            while let Ok(Some((_delta, entry))) = cursor.next_dfs() {
                let mut attrs = entry.attrs();
                while let Ok(Some(_attr)) = attrs.next() {
                    continue;
                }
            }
        }
    }
```

### PR DESCRIPTION
**Pull request by philipc**
The standard specifies that DW_FORM_indirect only has a single ULEB128,
which means it can't also contain the implicit constant. It also
doesn't make sense to want to combine these.

Fixes #501

### CODE REVIEW

File: src/read/unit.rs [hunk 1]
```diff
@@ -4751,6 +4756,27 @@ mod tests {
...
+    #[test]
+    fn test_parse_attribute_indirect_implicit_const() {
+        let encoding = Encoding {
+            format: Format::Dwarf32,
+            version: 4,
+            address_size: 4,
+        };
+        let mut buf = [0; 100];
+        let mut writable = &mut buf[..];
+        leb128::write::unsigned(&mut writable, constants::DW_FORM_implicit_const.0.into())
```
Comment (bjorn3) [inline src/read/unit.rs:4768]:
```suggestion
        leb128::write::unsigned(&mut &mut buf[..], constants::DW_FORM_implicit_const.0.into())
```

Comment (philipc) [reply src/read/unit.rs:4768]: Yep, thanks. This is old copy+paste test code though, so going to leave it how it is for consistency.
